# Generated by Django 2.1.5 on 2019-06-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_auto_20190610_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default=True, upload_to='photo/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stream',
            field=models.CharField(choices=[('1', 'CSE'), ('2', 'ECE'), ('3', 'MINING')], default=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='video_file',
            field=models.FileField(default=True, max_length=200, upload_to='video/'),
        ),
    ]
